http://studylog.hateblo.jp/entry/2015/08/27/225017

In [1]:
#!/usr/bin/env python
# coding:utf-8
"""
[1,2,3]というベクトルを与え、中の数字をそれぞれ2倍にして返すモデルを作りたい
"""
import numpy as np
import chainer.functions as F
from chainer import Variable, FunctionSet, optimizers

#モデルを作る
model = F.Linear(3,3)

#これがモデルに与えるベクトル
data = np.array([[1,2,3]] , dtype=np.float32)

x = Variable(np.array(data))

#ここでモデルにベクトルを投げて、加工させている
y = model(x)

#モデルが加工したベクトルを表示
print(y.data)

[[ 2.98616242  0.201491   -1.17733014]]


In [2]:
#!/usr/bin/env python
# coding:utf-8
"""
[1,2,3]というベクトルを与え、中の数字をそれぞれ2倍になるよう,50回繰り返す
"""
import numpy as np
import chainer.functions as F
from chainer import Variable, FunctionSet, optimizers

#モデル定義
model = F.Linear(3,3)
optimizer = optimizers.SGD()
optimizer.setup(model)


#学習させる回数
times = 50


#与えるベクトル  これが[2,4,6]になって返ってきて欲しい
x = Variable(np.array([[1, 2, 3]], dtype=np.float32))

#正解ベクトルの[2,4,6]
t = Variable(np.array([[2, 4, 6]], dtype=np.float32))

#ここから50回ループ
for i in range(0,times):
    optimizer.zero_grads()

    #ここでモデルに予測させている
    y = model(x)

    #モデルが出した答えを表示
    print(y.data)

    #お馬鹿なモデルが出した答えと、本当の答え([2,4,6])がどのくらい違っているか計算する
    loss = F.mean_squared_error(y, t)

    #その値をモデルに見せて「全然違うじゃねーか！もっと近づけろ！」と学習させる
    loss.backward()
    optimizer.update()

    #最初に戻って繰り返す

[[ 0.74795145 -1.16253698  2.68714643]]
[[ 0.87315619 -0.64628333  3.01843166]]
[[ 0.98584074 -0.181655    3.31658864]]
[[ 1.08725655  0.23651047  3.58492947]]
[[ 1.17853093  0.61285949  3.82643676]]
[[ 1.2606777   0.95157355  4.0437932 ]]
[[ 1.33460987  1.2564162   4.23941374]]
[[ 1.40114903  1.53077459  4.41547203]]
[[ 1.46103418  1.77769709  4.5739255 ]]
[[ 1.51493073  1.99992728  4.71653223]]
[[ 1.56343758  2.19993472  4.84487915]]
[[ 1.60709369  2.37994123  4.96039104]]
[[ 1.64638436  2.54194713  5.06435204]]
[[ 1.68174589  2.68775249  5.15791655]]
[[ 1.71357119  2.81897712  5.24212456]]
[[ 1.7422142   2.93707943  5.31791258]]
[[ 1.76799285  3.04337144  5.3861208 ]]
[[ 1.7911936   3.13903427  5.44750929]]
[[ 1.81207442  3.22513103  5.50275803]]
[[ 1.83086681  3.30261803  5.55248213]]
[[ 1.84778035  3.37235618  5.59723425]]
[[ 1.86300194  3.43512058  5.63751078]]
[[ 1.87670183  3.49160838  5.67375994]]
[[ 1.88903153  3.54244757  5.70638371]]
[[ 1.90012836  3.58820271  5.73574495]]
