p118

In [1]:
x=3*5
x

15

In [2]:
x=3*5
print(x)

15


In [5]:
import numpy as np
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [4]:
b = np.array(np.arange(10))
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
c = b.reshape(2,5)
c

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [5]:
a = np.arange(4).reshape(2,2)
a

array([[0, 1],
       [2, 3]])

In [5]:
b = np.arange(3,7).reshape(2,2)
b

array([[3, 4],
       [5, 6]])

In [6]:
a+b

array([[3, 5],
       [7, 9]])

In [7]:
a.T

array([[0, 2],
       [1, 3]])

In [8]:
a.T+b

array([[3, 6],
       [6, 9]])

In [9]:
a-b

array([[-3, -3],
       [-3, -3]])

In [10]:
np.dot(a,b)

array([[ 5,  6],
       [21, 26]])

In [7]:
v = np.array([10, 20])
np.dot(a,v)
np.dot(v,a)

array([40, 70])

In [30]:
# インデクシング
v = np.arange(10, 15)
v[:-1]
a = np.arange(1,5).reshape(2,2)
a
u = a[:,1]
u
ii = np.array([2,3])
v[ii]
w = np.array([False,False,False,True,True])
v[w]
# ブロードキャスティング
a*2
np.exp(a)
v<13
# インデクシングとブロードキャスティングを組み合わせた例
v[v<13]

array([10, 11, 12])

In [39]:
# 行列の結合の例
a = np.arange(6).reshape(2,3)
b = np.arange(6,12).reshape(2,3)
a
b
np.c_[a,b]
np.r_[a,b]
c = np.arange(3)
d = np.arange(3, 6)
c
d
np.c_[c, d]
np.r_[c, d]

array([0, 1, 2, 3, 4, 5])

In [52]:
# 疎行列の計算の例
from scipy import sparse
a = sparse.lil_matrix((5,5))
a[0,0]=1; a[1,2]=2; a[3,4]=3; a[4,4]=4
a.todense()
b = a.tocsr()
b.getrow(1).todense()
v = np.array([1,2,3,4,5])
a.dot(v)

array([  1.,   6.,   0.,  15.,  20.])

In [6]:
# matplotlib による可視化
# 折れ線グラフ
import matplotlib.pyplot as plt
x = [1,2,3,4]
y = [3,5,4,7]
plt.plot(x,y)
plt.show()

In [11]:
x = np.linspace(-5,5,100)
y = x**2
plt.plot(x,y)
plt.show()

In [13]:
# 例8
x = [1,2,3,4]
y = [3,5,4,7]
plt.scatter(x, y)
plt.show()

In [17]:
# 例9 & 10 remix
x = np.array([1,2,3])
y1 = np.array([2,3,4])
y2 = np.array([7,6,5])
plt.scatter(x, y1, marker="o", c ="b")
plt.scatter(x, y2, marker="+", c ="r")
plt.show()

In [21]:
# 例11
x = np.array([1,2,3])
y = np.array([4,5,6])
X, Y = np.meshgrid(x,y)
X
Y
X.ravel()
Y.ravel()

array([4, 4, 4, 5, 5, 5, 6, 6, 6])

In [31]:
# 例12~15

x = np.linspace(-5,5,200)
y = np.linspace(-5,5,200)
X, Y = np.meshgrid(x, y)
Z = X.ravel()**2 - Y.ravel()**2
#plt.contourf(X, Y, Z.reshape(X.shape))
#plt.contourf(X, Y, Z.reshape(X.shape), levels = [-20,-10,0,10,20],colors = ["r","g","b","y"])
plt.contour(X, Y, Z.reshape(X.shape), colors = "k")

plt.show()

# sckit-learn 入門

In [41]:
"""
p-128 リスト1 人工的データを使った線形回帰のプログラム
標準出力に,係数,切片,スコア(決定係数)を表示し,点群と回帰直線をグラフにして可視化する
"""
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model, datasets

# 乱数によりデータを生成
np.random.seed(0)
regdata = datasets.make_regression(100, 1, noise=20.0)

# 学習を行いモデルのパラメータを表示
lin = linear_model.LinearRegression()
lin.fit(regdata[0], regdata[1])
print("coef and intercept :", lin.coef_, lin.intercept_)
print("score :", lin.score(regdata[0], regdata[1]))

# グラフを描画
xr = [-2.5, 2.5]
plt.plot(xr, lin.coef_ * xr + lin.intercept_)
plt.scatter(regdata[0], regdata[1])

plt.show()

coef and intercept : [ 42.85335573] -1.62836365406
score : 0.803335728656


In [ ]:
"""
p-129 リスト2 糖尿病データを使った線形回帰のプログラム
標準出力に,係数,切片,スコア(決定係数)を表示し,点群と回帰直線をグラフにして可視化する
"""