p118

In [1]:
x=3*5
x

15

In [2]:
x=3*5
print(x)

15


In [2]:
import numpy as np
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [4]:
b = np.array(np.arange(10))
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
c = b.reshape(2,5)
c

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [4]:
a = np.arange(4).reshape(2,2)
a

array([[0, 1],
       [2, 3]])

In [5]:
b = np.arange(3,7).reshape(2,2)
b

array([[3, 4],
       [5, 6]])

In [6]:
a+b

array([[3, 5],
       [7, 9]])

In [7]:
a.T

array([[0, 2],
       [1, 3]])

In [8]:
a.T+b

array([[3, 6],
       [6, 9]])

In [9]:
a-b

array([[-3, -3],
       [-3, -3]])

In [10]:
np.dot(a,b)

array([[ 5,  6],
       [21, 26]])